name: Build and Deploy java jsf app to azure
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "gh720200520"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "Application/sampleWebApp"      # set this to the path to your web app project, defaults to the repository root
  JAVA_VERSION: '1.8'             # set this to the java version to use
  RESOURCEGROUPNAME: "gh720200520-rg"
  LOCATION: "South Central US"
  HOSTINGPLANNAME: "gh720200520-plan"
  APPINSIGHTLOCATION: "South Central US"
  SKU: "P1v2 Premium"
  WEBAPPTEMPLATENAME: "linux-webapp-template.json"

jobs:
  build:
    name: Build application source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up java ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build with maven
      run: |
        cd Application
        mvn package

    - name: Creating artifact directories
      run: |
        mkdir buildartifacts
        mkdir deploymenttemplates

    # Archive build artifact
    - name: Archive Build artifacts
      run: |
        zip -qq -r ./buildartifacts/target.zip ./Application/sampleWebApp/target/ROOT.war

    # uploading build artifacts
    - name: Upload target to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: buildartifacts
        path: buildartifacts

    # uploading test artifacts
    - name: Upload target to test artifacts
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: testartifacts
        path: ./Application/sampleWebApp.FunctionalTests/target

    # Archive Arm templates
    - name: Archive ArmTemplates
      run: |
        zip -qq -r ./deploymenttemplates/armtemplates.zip ./ArmTemplates

    # uploading Arm Templates to artifacts
    - name: Upload Arm templates to Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: deploymenttemplates
        path: deploymenttemplates

  Deploy:
    name: Deploy to azure web app
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    # Downloading build artifact
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: buildartifacts
        path: buildartifacts

    # Uzipping build artifacts
    - name: Unzipping Build artifact
      run: |
        unzip -qq ./buildartifacts/target.zip -d .

    # Downloading Arm Templates
    - name: Download Arm template
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: deploymenttemplates
        path: deploymenttemplates

    # Uzipping Arm template directory
    - name: Unzipping ARM template
      run: |
        unzip -qq ./deploymenttemplates/armtemplates.zip -d .

    # login to azure
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy Arm template
    - name: Deploy ARM Template
      uses: azure/CLI@v1
      continue-on-error: false
      with:
        inlineScript: |
          az group create --name "${{ env.RESOURCEGROUPNAME }}" --location "${{ env.LOCATION }}"
          az deployment group create --resource-group "${{ env.RESOURCEGROUPNAME }}" --template-file ./ArmTemplates/${{ env.WEBAPPTEMPLATENAME }} --parameters webAppName="${{ env.AZURE_WEBAPP_NAME }}" hostingPlanName="${{ env.HOSTINGPLANNAME }}" appInsightsLocation="${{ env.APPINSIGHTLOCATION }}" sku="${{ env.SKU }}"

    # Deploy web app on azure
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.war'

  FunctionalTests:
    name: Run Functional tests
    runs-on: windows-latest
    needs: Deploy
    steps:
    # Downloading test artifact
    - name: Download test Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: testartifacts
        path: testartifacts

    # Run functional tests
    - name: set up test environment and run tests
      continue-on-error: false
      run: |
        cd testartifacts
        java -DwebAppUrl="https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/" -DChromeWebDriver="$env:ChromeWebDriver" -cp SampleWebAppFunctionalTests-jar-with-dependencies.jar org.junit.platform.console.ConsoleLauncher --class-path SampleWebAppFunctionalTests-jar-with-dependencies.jar --scan-class-path --reports-dir reports --include-engine junit-vintage